# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='url',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
