# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0002_auto_20171003_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
