# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0003_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='gps',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='original_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='town', to='disasters.Town'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='disasters.Image'),
        ),
    ]
