# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0005_auto_20171003_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=200)),
                ('original_model', models.CharField(max_length=200)),
                ('accuracy', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='sample',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
