# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0006_auto_20171011_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='sample',
            field=models.ManyToManyField(to='disasters.Sample'),
        ),
    ]
