# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0007_model_sample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='sample',
            new_name='samples',
        ),
    ]
