# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0008_auto_20171013_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainsWith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='model',
            name='samples',
        ),
        migrations.AddField(
            model_name='trainswith',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='disasters.Model'),
        ),
        migrations.AddField(
            model_name='trainswith',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='disasters.Sample'),
        ),
        migrations.AddField(
            model_name='model',
            name='trains_with',
            field=models.ManyToManyField(through='disasters.TrainsWith', to='disasters.Sample'),
        ),
    ]
