# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0009_auto_20171013_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['accuracy']},
        ),
    ]
