# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0010_auto_20171013_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
