# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0011_auto_20171016_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='image',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
    ]
