# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0012_auto_20171017_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('address', models.CharField(max_length=200)),
                ('threshold', models.FloatField()),
                ('score', models.FloatField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disasters.Model')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disasters.Town')),
            ],
        ),
    ]
