# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0013_debris'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='town',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='town_sample', to='disasters.Town'),
            preserve_default=False,
        ),
    ]
